feat(misc): make envvars available with dotenv

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -5,3 +5,11 @@ set -xeuo pipefail
 if [ -n "$GIT_GLOBAL_HOOKS_PATH" -a -x "$GIT_GLOBAL_HOOKS_PATH/pre-commit" ]; then
   $GIT_GLOBAL_HOOKS_PATH/pre-commit
 fi
+
+echo "Looking for secrets in code..."
+DETECT_SECRETS_COMMAND="detect-secrets scan --exclude-lines exclude-from-detect-secrets $O63_DETECT_SECRETS_OPTS"
+if ! test "$(eval $DETECT_SECRETS_COMMAND | jq '.results | length')" = 0; then
+  echo 'Found secrets in code, aborting commit'
+  eval $DETECT_SECRETS_COMMAND | jq '.results'
+  exit 1
+fi
